### ISSUE TITLE
Adicionar licença livre

### ISSUE THREAD

**Issue by pizzamaker** [leocherubini/Artigo_Android_Arduino#1]
Faltou especificar no projeto uma licença. Minha sugestão: criar um arquivo de texto tipo COPYING.md ou LICENSE.md com o texto da licença AGPLv3: https://www.gnu.org/licenses/agpl.html

**Comment by leocherubini** [comment]
Boa tarde. Eu coloquei uma licença MIT.

2016-04-26 11:28 GMT-03:00 pizzaiolo notifications@github.com:

**Comment by pizzamaker** [comment]
Valeu! :)
